name: Deploy FastAPI to Azure App Service

on:
  push:
    branches:
      - main  # Trigger deployment on push to main branch

jobs:
  deploy:
    runs-on: self-hosted  # Self-hosted runner
    
    steps:
      # Step 1: Checkout the code
      - name: Checkout code
        uses: actions/checkout@v2

      # Step 2: Set up Python (FastAPI requires Python)
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      # Step 3: Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Step 4: Zip the FastAPI app
      - name: Zip the FastAPI app
        run: |
          zip -r fastapi-app.zip .  # Package your app into a zip file

      # Step 5: Log in to Azure using the publish profile
      - name: Deploy FastAPI app to Azure App Service
        run: |
          echo "${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}" > publish-profile.xml
          az webapp deployment source config-zip \
            --resource-group <YourResourceGroup> \
            --name <YourAppServiceName> \
            --src fastapi-app.zip \
            --publish-profile publish-profile.xml
        env:
          AZURE_WEBAPP_PUBLISH_PROFILE: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
