name: Deploy FastAPI to Azure App Service

on:
  push:
    branches:
      - main  # Trigger deployment on push to main branch

jobs:
  deploy:
    runs-on: self-hosted  # Self-hosted runner
    
    steps:
      # Step 1: Checkout the code
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Azure CLI v2.1.0 manually
        run: |
          sudo apt-get remove -y azure-cli || true
          wget https://azurecliprod.blob.core.windows.net/edge-archive/azure-cli_2.1.0-1~buster_all.deb
          sudo dpkg -i azure-cli_2.1.0-1~buster_all.deb
          sudo apt-get install -f -y

      # Step 2: Set up Python (FastAPI requires Python)
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      # Step 3: Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Step 4: Zip the FastAPI app
      - name: Zip the FastAPI app
        run: |
          zip -r fastapi_app.zip .  # Package your app into a zip file

      - name: Install Azure CLI if needed
        run: |
          az version || sudo apt-get update && sudo apt-get install -y azure-cli

      - name: Use host az to verify auth
        run: |
          echo "Using az on the host"
          az account show

      - name: Deploy ZIP using az CLI
        uses: azure/cli@v2.1.0
        with:
          inlineScript: |
            az webapp deployment source config-zip \
              --resource-group my-resource-group \
              --name my-fastapi-app \
              --src fastapi_app.zip
